# Generated by Django 4.1.1 on 2024-12-21 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Laboratorio')),
                ('ciudad', models.CharField(default='Santiago', max_length=255, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Chile', max_length=255, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('f_fabricacion', models.DateField(verbose_name='Fecha de Fabricación')),
                ('p_costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Costo')),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Director')),
                ('especialidad', models.CharField(default='General', max_length=255, verbose_name='Especialidad')),
                ('laboratorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio', verbose_name='Laboratorio Asociado')),
            ],
            options={
                'verbose_name': 'Director General',
                'verbose_name_plural': 'Directores Generales',
            },
        ),
    ]
